/* File automatically generated by genmdesc, don't change */

const char ppc64_cpu_desc [] = {
	"\x0\x0\x0\x0\x0\x0"	/* null entry */
	"\x0" "\x0" "\x0" "\x0" "\x4" "\x0" ""	/* nop */
	"\x0" "\x0" "\x0" "\x0" "\x4" "\x0" ""	/* relaxed_nop */
	"\x0" "ii\x0" "\x4" "\x0" ""	/* compare */
	"\x0" "i\x0" "\x0" "\xc" "\x0" ""	/* compare_imm */
	"\x0" "ff\x0" "\xc" "\x0" ""	/* fcompare */
	"\x0" "ii\x0" "\x4" "\x0" ""	/* lcompare */
	"\x0" "ii\x0" "\x4" "\x0" ""	/* icompare */
	"\x0" "i\x0" "\x0" "\xc" "\x0" ""	/* icompare_imm */
	"\x0" "i\x0" "\x0" "\xc" "\x0" ""	/* lcompare_imm */
	"\x0" "ii\x0" "\xc" "\x0" ""	/* setlret */
	"ii\x0" "\x0" "\x3c" "\x0" ""	/* localloc */
	"\x0" "b\x0" "\x0" "\x4" "\x0" ""	/* checkthis */
	"\x0" "\x0" "\x0" "\x0" "\x24" "c"	/* voidcall */
	"\x0" "i\x0" "\x0" "\x10" "c"	/* voidcall_reg */
	"\x0" "b\x0" "\x0" "\xc" "c"	/* voidcall_membase */
	"a\x0" "\x0" "\x0" "\x24" "c"	/* call */
	"ai\x0" "\x0" "\x10" "c"	/* call_reg */
	"ab\x0" "\x0" "\xc" "c"	/* call_membase */
	"g\x0" "\x0" "\x0" "\x24" "c"	/* fcall */
	"gi\x0" "\x0" "\x10" "c"	/* fcall_reg */
	"gb\x0" "\x0" "\xc" "c"	/* fcall_membase */
	"a\x0" "\x0" "\x0" "\x24" "c"	/* lcall */
	"ai\x0" "\x0" "\x10" "c"	/* lcall_reg */
	"ab\x0" "\x0" "\xc" "c"	/* lcall_membase */
	"\x0" "\x0" "\x0" "\x0" "\x10" "c"	/* vcall */
	"\x0" "i\x0" "\x0" "\x10" "c"	/* vcall_reg */
	"\x0" "b\x0" "\x0" "\xc" "c"	/* vcall_membase */
	"\x0" "\x0" "\x0" "\x0" "\x24" "c"	/* vcall2 */
	"\x0" "i\x0" "\x0" "\x10" "c"	/* vcall2_reg */
	"\x0" "b\x0" "\x0" "\xc" "c"	/* vcall2_membase */
	"i\x0" "\x0" "\x0" "\x14" "\x0" ""	/* iconst */
	"i\x0" "\x0" "\x0" "\x14" "\x0" ""	/* i8const */
	"f\x0" "\x0" "\x0" "\xc" "\x0" ""	/* r4const */
	"f\x0" "\x0" "\x0" "\x18" "\x0" ""	/* r8const */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" ""	/* label */
	"\x0" "i\x0" "\x0" "\x28" "\x0" ""	/* throw */
	"\x0" "i\x0" "\x0" "\x28" "\x0" ""	/* rethrow */
	"\x0" "i\x0" "\x0" "\xc" "\x0" ""	/* oparglist */
	"bi\x0" "\x0" "\xc" "\x0" ""	/* store_membase_reg */
	"bi\x0" "\x0" "\xc" "\x0" ""	/* storei1_membase_reg */
	"bi\x0" "\x0" "\xc" "\x0" ""	/* storei2_membase_reg */
	"bi\x0" "\x0" "\xc" "\x0" ""	/* storei4_membase_reg */
	"bi\x0" "\x0" "\xc" "\x0" ""	/* storei8_membase_reg */
	"bf\x0" "\x0" "\x10" "\x0" ""	/* storer4_membase_reg */
	"bf\x0" "\x0" "\xc" "\x0" ""	/* storer8_membase_reg */
	"ib\x0" "\x0" "\xc" "\x0" ""	/* load_membase */
	"ib\x0" "\x0" "\x10" "\x0" ""	/* loadi1_membase */
	"ib\x0" "\x0" "\xc" "\x0" ""	/* loadu1_membase */
	"ib\x0" "\x0" "\xc" "\x0" ""	/* loadi2_membase */
	"ib\x0" "\x0" "\xc" "\x0" ""	/* loadu2_membase */
	"ib\x0" "\x0" "\xc" "\x0" ""	/* loadi4_membase */
	"ib\x0" "\x0" "\xc" "\x0" ""	/* loadu4_membase */
	"ib\x0" "\x0" "\xc" "\x0" ""	/* loadi8_membase */
	"fb\x0" "\x0" "\xc" "\x0" ""	/* loadr4_membase */
	"fb\x0" "\x0" "\xc" "\x0" ""	/* loadr8_membase */
	"ibi\x0" "\x4" "\x0" ""	/* load_memindex */
	"ibi\x0" "\x8" "\x0" ""	/* loadi1_memindex */
	"ibi\x0" "\x4" "\x0" ""	/* loadu1_memindex */
	"ibi\x0" "\x4" "\x0" ""	/* loadi2_memindex */
	"ibi\x0" "\x4" "\x0" ""	/* loadu2_memindex */
	"ibi\x0" "\x4" "\x0" ""	/* loadi4_memindex */
	"ibi\x0" "\x4" "\x0" ""	/* loadu4_memindex */
	"ibi\x0" "\x4" "\x0" ""	/* loadi8_memindex */
	"fbi\x0" "\x4" "\x0" ""	/* loadr4_memindex */
	"fbi\x0" "\x4" "\x0" ""	/* loadr8_memindex */
	"bii\x0" "\x4" "\x0" ""	/* store_memindex */
	"bii\x0" "\x4" "\x0" ""	/* storei1_memindex */
	"bii\x0" "\x4" "\x0" ""	/* storei2_memindex */
	"bii\x0" "\x4" "\x0" ""	/* storei4_memindex */
	"bii\x0" "\x4" "\x0" ""	/* storei8_memindex */
	"bii\x0" "\x8" "\x0" ""	/* storer4_memindex */
	"bii\x0" "\x4" "\x0" ""	/* storer8_memindex */
	"i\x0" "\x0" "\x0" "\x8" "\x0" ""	/* loadu4_mem */
	"ii\x0" "\x0" "\x4" "\x0" ""	/* move */
	"ff\x0" "\x0" "\x4" "\x0" ""	/* fmove */
	"ii\x0" "\x0" "\x4" "\x0" ""	/* add_imm */
	"ii\x0" "\x0" "\x4" "\x0" ""	/* sub_imm */
	"ii\x0" "\x0" "\x4" "\x0" ""	/* mul_imm */
	"iii\x0" "\x14" "\x0" ""	/* div_imm */
	"iii\x0" "\xc" "\x0" ""	/* div_un_imm */
	"iii\x0" "\x1c" "\x0" ""	/* rem_imm */
	"iii\x0" "\x10" "\x0" ""	/* rem_un_imm */
	"ii\x0" "\x0" "\x4" "\x0" ""	/* and_imm */
	"ii\x0" "\x0" "\x4" "\x0" ""	/* or_imm */
	"ii\x0" "\x0" "\x4" "\x0" ""	/* xor_imm */
	"ii\x0" "\x0" "\x4" "\x0" ""	/* shl_imm */
	"ii\x0" "\x0" "\x4" "\x0" ""	/* shr_imm */
	"ii\x0" "\x0" "\x4" "\x0" ""	/* shr_un_imm */
	"\x0" "\x0" "\x0" "\x0" "\x4" "\x0" ""	/* br */
	"\x0" "\x0" "\x0" "\x0" "\x60" "\x0" ""	/* jmp */
	"\x0" "\x0" "\x0" "\x0" "\x4" "\x0" ""	/* break */
	"i\x0" "\x0" "\x0" "\xc" "\x0" ""	/* ceq */
	"i\x0" "\x0" "\x0" "\xc" "\x0" ""	/* cgt */
	"i\x0" "\x0" "\x0" "\xc" "\x0" ""	/* cgt.un */
	"i\x0" "\x0" "\x0" "\xc" "\x0" ""	/* clt */
	"i\x0" "\x0" "\x0" "\xc" "\x0" ""	/* clt.un */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* cond_exc_eq */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* cond_exc_ge */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* cond_exc_gt */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* cond_exc_le */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* cond_exc_lt */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* cond_exc_ne_un */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* cond_exc_ge_un */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* cond_exc_gt_un */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* cond_exc_le_un */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* cond_exc_lt_un */
	"\x0" "\x0" "\x0" "\x0" "\xc" "\x0" ""	/* cond_exc_ov */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* cond_exc_no */
	"\x0" "\x0" "\x0" "\x0" "\xc" "\x0" ""	/* cond_exc_c */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* cond_exc_nc */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* cond_exc_ieq */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* cond_exc_ige */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* cond_exc_igt */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* cond_exc_ile */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* cond_exc_ilt */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* cond_exc_ine_un */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* cond_exc_ige_un */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* cond_exc_igt_un */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* cond_exc_ile_un */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* cond_exc_ilt_un */
	"\x0" "\x0" "\x0" "\x0" "\xc" "\x0" ""	/* cond_exc_iov */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* cond_exc_ino */
	"\x0" "\x0" "\x0" "\x0" "\xc" "\x0" ""	/* cond_exc_ic */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* cond_exc_inc */
	"iii\x0" "\x4" "\x0" ""	/* long_add */
	"iii\x0" "\x4" "\x0" ""	/* long_sub */
	"iii\x0" "\x4" "\x0" ""	/* long_mul */
	"iii\x0" "\x28" "\x0" ""	/* long_div */
	"iii\x0" "\x10" "\x0" ""	/* long_div_un */
	"iii\x0" "\x30" "\x0" ""	/* long_rem */
	"iii\x0" "\x18" "\x0" ""	/* long_rem_un */
	"iii\x0" "\x4" "\x0" ""	/* long_and */
	"iii\x0" "\x4" "\x0" ""	/* long_or */
	"iii\x0" "\x4" "\x0" ""	/* long_xor */
	"iii\x0" "\x4" "\x0" ""	/* long_shl */
	"iii\x0" "\x4" "\x0" ""	/* long_shr */
	"iii\x0" "\x4" "\x0" ""	/* long_shr_un */
	"ii\x0" "\x0" "\x4" "\x0" ""	/* long_neg */
	"ii\x0" "\x0" "\x4" "\x0" ""	/* long_not */
	"ii\x0" "\x0" "\x4" "\x0" ""	/* long_conv_to_i1 */
	"ii\x0" "\x0" "\x4" "\x0" ""	/* long_conv_to_i2 */
	"ii\x0" "\x0" "\x4" "\x0" ""	/* long_conv_to_i4 */
	"fi\x0" "\x0" "\x10" "\x0" ""	/* long_conv_to_r4 */
	"fi\x0" "\x0" "\xc" "\x0" ""	/* long_conv_to_r8 */
	"ii\x0" "\x0" "\x0" "\x0" ""	/* long_conv_to_u4 */
	"ii\x0" "\x0" "\x4" "\x0" ""	/* long_conv_to_u2 */
	"ii\x0" "\x0" "\x4" "\x0" ""	/* long_conv_to_u1 */
	"iii\x0" "\x20" "\x0" ""	/* long_conv_to_ovf_i */
	"iii\x0" "\x10" "\x0" ""	/* long_add_ovf */
	"iii\x0" "\x10" "\x0" ""	/* long_add_ovf_un */
	"iii\x0" "\x10" "\x0" ""	/* long_mul_ovf */
	"iii\x0" "\x10" "\x0" ""	/* long_mul_ovf_un */
	"iii\x0" "\x10" "\x0" ""	/* long_sub_ovf */
	"iii\x0" "\x10" "\x0" ""	/* long_sub_ovf_un */
	"i\x0" "\x0" "\x0" "\xc" "\x0" ""	/* long_ceq */
	"i\x0" "\x0" "\x0" "\xc" "\x0" ""	/* long_cgt */
	"i\x0" "\x0" "\x0" "\xc" "\x0" ""	/* long_cgt_un */
	"i\x0" "\x0" "\x0" "\xc" "\x0" ""	/* long_clt */
	"i\x0" "\x0" "\x0" "\xc" "\x0" ""	/* long_clt_un */
	"fii\x0" "\x25" "\x0" ""	/* long_conv_to_r_un */
	"ii\x0" "\x0" "\x4" "1"	/* long_add_imm */
	"ii\x0" "\x0" "\x4" "1"	/* long_sub_imm */
	"ii\x0" "\x0" "\x4" "\x0" ""	/* long_mul_imm */
	"ii\x0" "\x0" "\x4" "1"	/* long_and_imm */
	"ii\x0" "\x0" "\x4" "1"	/* long_or_imm */
	"ii\x0" "\x0" "\x4" "1"	/* long_xor_imm */
	"ii\x0" "\x0" "\x4" "\x0" ""	/* long_shl_imm */
	"ii\x0" "\x0" "\x4" "\x0" ""	/* long_shr_imm */
	"ii\x0" "\x0" "\x4" "\x0" ""	/* long_shr_un_imm */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* long_beq */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* long_bge */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* long_bgt */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* long_ble */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* long_blt */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* long_bne_un */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* long_bge_un */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* long_bgt_un */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* long_ble_un */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* long_blt_un */
	"iii\x0" "\x4" "\x0" ""	/* int_add */
	"iii\x0" "\x4" "\x0" ""	/* int_sub */
	"iii\x0" "\x4" "\x0" ""	/* int_mul */
	"iii\x0" "\x28" "\x0" ""	/* int_div */
	"iii\x0" "\x10" "\x0" ""	/* int_div_un */
	"iii\x0" "\x30" "\x0" ""	/* int_rem */
	"iii\x0" "\x18" "\x0" ""	/* int_rem_un */
	"iii\x0" "\x4" "\x0" ""	/* int_and */
	"iii\x0" "\x4" "\x0" ""	/* int_or */
	"iii\x0" "\x4" "\x0" ""	/* int_xor */
	"iii\x0" "\x4" "\x0" ""	/* int_shl */
	"iii\x0" "\x4" "\x0" ""	/* int_shr */
	"iii\x0" "\x4" "\x0" ""	/* int_shr_un */
	"ii\x0" "\x0" "\x4" "\x0" ""	/* int_neg */
	"ii\x0" "\x0" "\x4" "\x0" ""	/* int_not */
	"ii\x0" "\x0" "\x8" "\x0" ""	/* int_conv_to_i1 */
	"ii\x0" "\x0" "\x8" "\x0" ""	/* int_conv_to_i2 */
	"ii\x0" "\x0" "\x4" "\x0" ""	/* int_conv_to_i4 */
	"fi\x0" "\x0" "\x14" "\x0" ""	/* int_conv_to_r4 */
	"fi\x0" "\x0" "\x10" "\x0" ""	/* int_conv_to_r8 */
	"ii\x0" "\x0" "\x4" "\x0" ""	/* int_conv_to_u4 */
	"ii\x0" "\x0" "\x8" "\x0" ""	/* int_conv_to_u2 */
	"ii\x0" "\x0" "\x4" "\x0" ""	/* int_conv_to_u1 */
	"iii\x0" "\x10" "\x0" ""	/* int_add_ovf */
	"iii\x0" "\x10" "\x0" ""	/* int_add_ovf_un */
	"iii\x0" "\x10" "\x0" ""	/* int_mul_ovf */
	"iii\x0" "\x10" "\x0" ""	/* int_mul_ovf_un */
	"iii\x0" "\x10" "\x0" ""	/* int_sub_ovf */
	"iii\x0" "\x10" "\x0" ""	/* int_sub_ovf_un */
	"iii\x0" "\x4" "\x0" ""	/* int_adc */
	"ii\x0" "\x0" "\xc" "\x0" ""	/* int_adc_imm */
	"iii\x0" "\x4" "\x0" ""	/* int_sbb */
	"ii\x0" "\x0" "\xc" "\x0" ""	/* int_sbb_imm */
	"iii\x0" "\x4" "\x0" ""	/* int_addcc */
	"iii\x0" "\x4" "\x0" ""	/* int_subcc */
	"ii\x0" "\x0" "\x4" "\x0" ""	/* int_add_imm */
	"ii\x0" "\x0" "\xc" "\x0" ""	/* int_sub_imm */
	"ii\x0" "\x0" "\xc" "\x0" ""	/* int_mul_imm */
	"ii\x0" "\x0" "\x14" "\x0" ""	/* int_div_imm */
	"ii\x0" "\x0" "\xc" "\x0" ""	/* int_div_un_imm */
	"ii\x0" "\x0" "\x1c" "\x0" ""	/* int_rem_imm */
	"ii\x0" "\x0" "\x10" "\x0" ""	/* int_rem_un_imm */
	"ii\x0" "\x0" "\xc" "\x0" ""	/* int_and_imm */
	"ii\x0" "\x0" "\xc" "\x0" ""	/* int_or_imm */
	"ii\x0" "\x0" "\xc" "\x0" ""	/* int_xor_imm */
	"ii\x0" "\x0" "\x8" "\x0" ""	/* int_shl_imm */
	"ii\x0" "\x0" "\x8" "\x0" ""	/* int_shr_imm */
	"ii\x0" "\x0" "\x8" "\x0" ""	/* int_shr_un_imm */
	"i\x0" "\x0" "\x0" "\xc" "\x0" ""	/* int_ceq */
	"i\x0" "\x0" "\x0" "\xc" "\x0" ""	/* int_cgt */
	"i\x0" "\x0" "\x0" "\xc" "\x0" ""	/* int_cgt_un */
	"i\x0" "\x0" "\x0" "\xc" "\x0" ""	/* int_clt */
	"i\x0" "\x0" "\x0" "\xc" "\x0" ""	/* int_clt_un */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* int_beq */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* int_bge */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* int_bgt */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* int_ble */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* int_blt */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* int_bne_un */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* int_bge_un */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* int_bgt_un */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* int_ble_un */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* int_blt_un */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* float_beq */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* float_bge */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* float_bgt */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* float_ble */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* float_blt */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* float_bne_un */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* float_bge_un */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* float_bgt_un */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* float_ble_un */
	"\x0" "\x0" "\x0" "\x0" "\x8" "\x0" ""	/* float_blt_un */
	"fff\x0" "\x4" "\x0" ""	/* float_add */
	"fff\x0" "\x4" "\x0" ""	/* float_sub */
	"fff\x0" "\x4" "\x0" ""	/* float_mul */
	"fff\x0" "\x4" "\x0" ""	/* float_div */
	"fff\x0" "\x4" "\x0" ""	/* float_div_un */
	"fff\x0" "\x10" "\x0" ""	/* float_rem */
	"fff\x0" "\x10" "\x0" ""	/* float_rem_un */
	"ff\x0" "\x0" "\x4" "\x0" ""	/* float_neg */
	"ff\x0" "\x0" "\x4" "\x0" ""	/* float_not */
	"if\x0" "\x0" "\x28" "\x0" ""	/* float_conv_to_i1 */
	"if\x0" "\x0" "\x28" "\x0" ""	/* float_conv_to_i2 */
	"if\x0" "\x0" "\x28" "\x0" ""	/* float_conv_to_i4 */
	"if\x0" "\x0" "\x28" "\x0" ""	/* float_conv_to_i8 */
	"ff\x0" "\x0" "\x4" "\x0" ""	/* float_conv_to_r4 */
	"if\x0" "\x0" "\x28" "\x0" ""	/* float_conv_to_u4 */
	"if\x0" "\x0" "\x28" "\x0" ""	/* float_conv_to_u8 */
	"if\x0" "\x0" "\x28" "\x0" ""	/* float_conv_to_u2 */
	"if\x0" "\x0" "\x28" "\x0" ""	/* float_conv_to_u1 */
	"if\x0" "\x0" "\x28" "\x0" ""	/* float_conv_to_i */
	"iff\x0" "\x10" "\x0" ""	/* float_ceq */
	"iff\x0" "\x10" "\x0" ""	/* float_cgt */
	"iff\x0" "\x14" "\x0" ""	/* float_cgt_un */
	"iff\x0" "\x10" "\x0" ""	/* float_clt */
	"iff\x0" "\x14" "\x0" ""	/* float_clt_un */
	"if\x0" "\x0" "\x24" "\x0" ""	/* float_conv_to_u */
	"ff\x0" "\x0" "\x0" "\x0" ""	/* ckfinite */
	"i\x0" "\x0" "\x0" "\x14" "\x0" ""	/* jump_table */
	"i\x0" "\x0" "\x0" "\x8" "\x0" ""	/* aot_const */
	"ib\x0" "\x0" "\x20" "\x0" ""	/* got_entry */
	"\x0" "\x0" "\x0" "\x0" "\xc" "c"	/* call_handler */
	"\x0" "\x0" "\x0" "\x0" "\x10" "\x0" ""	/* start_handler */
	"\x0" "i\x0" "\x0" "\x14" "\x0" ""	/* endfilter */
	"\x0" "\x0" "\x0" "\x0" "\x14" "\x0" ""	/* endfinally */
	"iii\x0" "\xc" "\x0" ""	/* bigmul */
	"iii\x0" "\xc" "\x0" ""	/* bigmul_un */
	"iii\x0" "\x4" "\x0" ""	/* adc */
	"iii\x0" "\x4" "\x0" ""	/* sbb */
	"iii\x0" "\x4" "\x0" ""	/* addcc */
	"ii\x0" "\x0" "\x4" "\x0" ""	/* addcc_imm */
	"iii\x0" "\x4" "\x0" ""	/* subcc */
	"\x0" "i\x0" "\x0" "\x8" "\x0" ""	/* br_reg */
	"ii\x0" "\x0" "\x4" "\x0" ""	/* sext_i4 */
	"ii\x0" "\x0" "\x4" "\x0" ""	/* zext_i4 */
	"iii\x0" "\x10" "\x0" ""	/* add_ovf_carry */
	"iii\x0" "\x10" "\x0" ""	/* sub_ovf_carry */
	"iii\x0" "\x10" "\x0" ""	/* add_ovf_un_carry */
	"iii\x0" "\x10" "\x0" ""	/* sub_ovf_un_carry */
	"ff\x0" "\x0" "\x4" "\x0" ""	/* sqrt */
	"i\x0" "\x0" "\x0" "\x8" "\x0" ""	/* tls_get */
	"i\x0" "\x0" "\x0" "\x20" "\x0" ""	/* load_gotaddr */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" ""	/* dummy_use */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" ""	/* dummy_store */
	"\x0" "\x0" "\x0" "\x0" "\x0" "\x0" ""	/* not_reached */
	"\x0" "i\x0" "\x0" "\x0" "\x0" ""	/* not_null */
	"ibi\x0" "\x14" "\x0" ""	/* atomic_add_new_i4 */
	"ibi\x0" "\x14" "\x0" ""	/* atomic_add_new_i8 */
	"\x0" "\x0" "\x0" "\x0" "\x4" "\x0" ""	/* memory_barrier */
	"ibii\x1e" "\x0" ""	/* atomic_cas_i4 */
	"ibii\x1e" "\x0" ""	/* atomic_cas_i8 */
	"ii\x0" "\x0" "\x4" "\x0" ""	/* ppc_subfic */
	"ii\x0" "\x0" "\x4" "\x0" ""	/* ppc_subfze */
	"\x0" "i\x0" "\x0" "\x10" "\x0" ""	/* ppc_check_finite */
};

const guint16 ppc64_cpu_desc_idx [] = {
	0,	/* load */
	0,	/* ldaddr */
	0,	/* store */
	6,	/* nop */
	0,	/* hard_nop */
	12,	/* relaxed_nop */
	0,	/* phi */
	0,	/* fphi */
	0,	/* vphi */
	18,	/* compare */
	24,	/* compare_imm */
	30,	/* fcompare */
	36,	/* lcompare */
	42,	/* icompare */
	48,	/* icompare_imm */
	54,	/* lcompare_imm */
	0,	/* local */
	0,	/* arg */
	0,	/* outarg_vt */
	0,	/* outarg_vtretaddr */
	0,	/* setret */
	0,	/* setfret */
	60,	/* setlret */
	66,	/* localloc */
	0,	/* localloc_imm */
	72,	/* checkthis */
	0,	/* seq_point */
	0,	/* implicit_exception */
	78,	/* voidcall */
	0,	/* voidcallvirt */
	84,	/* voidcall_reg */
	90,	/* voidcall_membase */
	96,	/* call */
	102,	/* call_reg */
	108,	/* call_membase */
	0,	/* callvirt */
	114,	/* fcall */
	0,	/* fcallvirt */
	120,	/* fcall_reg */
	126,	/* fcall_membase */
	132,	/* lcall */
	0,	/* lcallvirt */
	138,	/* lcall_reg */
	144,	/* lcall_membase */
	150,	/* vcall */
	0,	/* vcallvirt */
	156,	/* vcall_reg */
	162,	/* vcall_membase */
	168,	/* vcall2 */
	174,	/* vcall2_reg */
	180,	/* vcall2_membase */
	0,	/* dyn_call */
	186,	/* iconst */
	192,	/* i8const */
	198,	/* r4const */
	204,	/* r8const */
	0,	/* regvar */
	0,	/* regoffset */
	0,	/* vtarg_addr */
	210,	/* label */
	0,	/* switch */
	216,	/* throw */
	222,	/* rethrow */
	228,	/* oparglist */
	234,	/* store_membase_reg */
	240,	/* storei1_membase_reg */
	246,	/* storei2_membase_reg */
	252,	/* storei4_membase_reg */
	258,	/* storei8_membase_reg */
	264,	/* storer4_membase_reg */
	270,	/* storer8_membase_reg */
	0,	/* store_membase_imm */
	0,	/* storei1_membase_imm */
	0,	/* storei2_membase_imm */
	0,	/* storei4_membase_imm */
	0,	/* storei8_membase_imm */
	0,	/* storex_membase */
	0,	/* storev_membase */
	276,	/* load_membase */
	282,	/* loadi1_membase */
	288,	/* loadu1_membase */
	294,	/* loadi2_membase */
	300,	/* loadu2_membase */
	306,	/* loadi4_membase */
	312,	/* loadu4_membase */
	318,	/* loadi8_membase */
	324,	/* loadr4_membase */
	330,	/* loadr8_membase */
	0,	/* loadx_membase */
	0,	/* loadv_membase */
	336,	/* load_memindex */
	342,	/* loadi1_memindex */
	348,	/* loadu1_memindex */
	354,	/* loadi2_memindex */
	360,	/* loadu2_memindex */
	366,	/* loadi4_memindex */
	372,	/* loadu4_memindex */
	378,	/* loadi8_memindex */
	384,	/* loadr4_memindex */
	390,	/* loadr8_memindex */
	396,	/* store_memindex */
	402,	/* storei1_memindex */
	408,	/* storei2_memindex */
	414,	/* storei4_memindex */
	420,	/* storei8_memindex */
	426,	/* storer4_memindex */
	432,	/* storer8_memindex */
	0,	/* load_mem */
	0,	/* loadu1_mem */
	0,	/* loadu2_mem */
	0,	/* loadi4_mem */
	438,	/* loadu4_mem */
	0,	/* loadi8_mem */
	0,	/* store_mem_imm */
	444,	/* move */
	0,	/* lmove */
	450,	/* fmove */
	0,	/* vmove */
	0,	/* vzero */
	456,	/* add_imm */
	462,	/* sub_imm */
	468,	/* mul_imm */
	474,	/* div_imm */
	480,	/* div_un_imm */
	486,	/* rem_imm */
	492,	/* rem_un_imm */
	498,	/* and_imm */
	504,	/* or_imm */
	510,	/* xor_imm */
	516,	/* shl_imm */
	522,	/* shr_imm */
	528,	/* shr_un_imm */
	534,	/* br */
	540,	/* jmp */
	0,	/* tailcall */
	546,	/* break */
	552,	/* ceq */
	558,	/* cgt */
	564,	/* cgt.un */
	570,	/* clt */
	576,	/* clt.un */
	582,	/* cond_exc_eq */
	588,	/* cond_exc_ge */
	594,	/* cond_exc_gt */
	600,	/* cond_exc_le */
	606,	/* cond_exc_lt */
	612,	/* cond_exc_ne_un */
	618,	/* cond_exc_ge_un */
	624,	/* cond_exc_gt_un */
	630,	/* cond_exc_le_un */
	636,	/* cond_exc_lt_un */
	642,	/* cond_exc_ov */
	648,	/* cond_exc_no */
	654,	/* cond_exc_c */
	660,	/* cond_exc_nc */
	666,	/* cond_exc_ieq */
	672,	/* cond_exc_ige */
	678,	/* cond_exc_igt */
	684,	/* cond_exc_ile */
	690,	/* cond_exc_ilt */
	696,	/* cond_exc_ine_un */
	702,	/* cond_exc_ige_un */
	708,	/* cond_exc_igt_un */
	714,	/* cond_exc_ile_un */
	720,	/* cond_exc_ilt_un */
	726,	/* cond_exc_iov */
	732,	/* cond_exc_ino */
	738,	/* cond_exc_ic */
	744,	/* cond_exc_inc */
	750,	/* long_add */
	756,	/* long_sub */
	762,	/* long_mul */
	768,	/* long_div */
	774,	/* long_div_un */
	780,	/* long_rem */
	786,	/* long_rem_un */
	792,	/* long_and */
	798,	/* long_or */
	804,	/* long_xor */
	810,	/* long_shl */
	816,	/* long_shr */
	822,	/* long_shr_un */
	828,	/* long_neg */
	834,	/* long_not */
	840,	/* long_conv_to_i1 */
	846,	/* long_conv_to_i2 */
	852,	/* long_conv_to_i4 */
	0,	/* long_conv_to_i8 */
	858,	/* long_conv_to_r4 */
	864,	/* long_conv_to_r8 */
	870,	/* long_conv_to_u4 */
	0,	/* long_conv_to_u8 */
	876,	/* long_conv_to_u2 */
	882,	/* long_conv_to_u1 */
	0,	/* long_conv_to_i */
	888,	/* long_conv_to_ovf_i */
	0,	/* long_conv_to_ovf_u */
	894,	/* long_add_ovf */
	900,	/* long_add_ovf_un */
	906,	/* long_mul_ovf */
	912,	/* long_mul_ovf_un */
	918,	/* long_sub_ovf */
	924,	/* long_sub_ovf_un */
	0,	/* long_conv_to_ovf_i1_un */
	0,	/* long_conv_to_ovf_i2_un */
	0,	/* long_conv_to_ovf_i4_un */
	0,	/* long_conv_to_ovf_i8_un */
	0,	/* long_conv_to_ovf_u1_un */
	0,	/* long_conv_to_ovf_u2_un */
	0,	/* long_conv_to_ovf_u4_un */
	0,	/* long_conv_to_ovf_u8_un */
	0,	/* long_conv_to_ovf_i_un */
	0,	/* long_conv_to_ovf_u_un */
	0,	/* long_conv_to_ovf_i1 */
	0,	/* long_conv_to_ovf_u1 */
	0,	/* long_conv_to_ovf_i2 */
	0,	/* long_conv_to_ovf_u2 */
	0,	/* long_conv_to_ovf_i4 */
	0,	/* long_conv_to_ovf_u4 */
	0,	/* long_conv_to_ovf_i8 */
	0,	/* long_conv_to_ovf_u8 */
	930,	/* long_ceq */
	936,	/* long_cgt */
	942,	/* long_cgt_un */
	948,	/* long_clt */
	954,	/* long_clt_un */
	960,	/* long_conv_to_r_un */
	0,	/* long_conv_to_u */
	966,	/* long_add_imm */
	972,	/* long_sub_imm */
	978,	/* long_mul_imm */
	984,	/* long_and_imm */
	990,	/* long_or_imm */
	996,	/* long_xor_imm */
	1002,	/* long_shl_imm */
	1008,	/* long_shr_imm */
	1014,	/* long_shr_un_imm */
	0,	/* long_div_imm */
	0,	/* long_div_un_imm */
	0,	/* long_rem_imm */
	0,	/* long_rem_un_imm */
	1020,	/* long_beq */
	1026,	/* long_bge */
	1032,	/* long_bgt */
	1038,	/* long_ble */
	1044,	/* long_blt */
	1050,	/* long_bne_un */
	1056,	/* long_bge_un */
	1062,	/* long_bgt_un */
	1068,	/* long_ble_un */
	1074,	/* long_blt_un */
	0,	/* long_conv_to_r8_2 */
	0,	/* long_conv_to_r4_2 */
	0,	/* long_conv_to_r_un_2 */
	0,	/* long_conv_to_ovf_i4_2 */
	1080,	/* int_add */
	1086,	/* int_sub */
	1092,	/* int_mul */
	1098,	/* int_div */
	1104,	/* int_div_un */
	1110,	/* int_rem */
	1116,	/* int_rem_un */
	1122,	/* int_and */
	1128,	/* int_or */
	1134,	/* int_xor */
	1140,	/* int_shl */
	1146,	/* int_shr */
	1152,	/* int_shr_un */
	1158,	/* int_neg */
	1164,	/* int_not */
	1170,	/* int_conv_to_i1 */
	1176,	/* int_conv_to_i2 */
	1182,	/* int_conv_to_i4 */
	0,	/* int_conv_to_i8 */
	1188,	/* int_conv_to_r4 */
	1194,	/* int_conv_to_r8 */
	1200,	/* int_conv_to_u4 */
	0,	/* int_conv_to_u8 */
	0,	/* int_conv_to_r_un */
	0,	/* int_conv_to_u */
	1206,	/* int_conv_to_u2 */
	1212,	/* int_conv_to_u1 */
	0,	/* int_conv_to_i */
	0,	/* int_conv_to_ovf_i */
	0,	/* int_conv_to_ovf_u */
	1218,	/* int_add_ovf */
	1224,	/* int_add_ovf_un */
	1230,	/* int_mul_ovf */
	1236,	/* int_mul_ovf_un */
	1242,	/* int_sub_ovf */
	1248,	/* int_sub_ovf_un */
	0,	/* int_conv_to_ovf_i1_un */
	0,	/* int_conv_to_ovf_i2_un */
	0,	/* int_conv_to_ovf_i4_un */
	0,	/* int_conv_to_ovf_i8_un */
	0,	/* int_conv_to_ovf_u1_un */
	0,	/* int_conv_to_ovf_u2_un */
	0,	/* int_conv_to_ovf_u4_un */
	0,	/* int_conv_to_ovf_u8_un */
	0,	/* int_conv_to_ovf_i_un */
	0,	/* int_conv_to_ovf_u_un */
	0,	/* int_conv_to_ovf_i1 */
	0,	/* int_conv_to_ovf_u1 */
	0,	/* int_conv_to_ovf_i2 */
	0,	/* int_conv_to_ovf_u2 */
	0,	/* int_conv_to_ovf_i4 */
	0,	/* int_conv_to_ovf_u4 */
	0,	/* int_conv_to_ovf_i8 */
	0,	/* int_conv_to_ovf_u8 */
	1254,	/* int_adc */
	1260,	/* int_adc_imm */
	1266,	/* int_sbb */
	1272,	/* int_sbb_imm */
	1278,	/* int_addcc */
	1284,	/* int_subcc */
	1290,	/* int_add_imm */
	1296,	/* int_sub_imm */
	1302,	/* int_mul_imm */
	1308,	/* int_div_imm */
	1314,	/* int_div_un_imm */
	1320,	/* int_rem_imm */
	1326,	/* int_rem_un_imm */
	1332,	/* int_and_imm */
	1338,	/* int_or_imm */
	1344,	/* int_xor_imm */
	1350,	/* int_shl_imm */
	1356,	/* int_shr_imm */
	1362,	/* int_shr_un_imm */
	1368,	/* int_ceq */
	1374,	/* int_cgt */
	1380,	/* int_cgt_un */
	1386,	/* int_clt */
	1392,	/* int_clt_un */
	1398,	/* int_beq */
	1404,	/* int_bge */
	1410,	/* int_bgt */
	1416,	/* int_ble */
	1422,	/* int_blt */
	1428,	/* int_bne_un */
	1434,	/* int_bge_un */
	1440,	/* int_bgt_un */
	1446,	/* int_ble_un */
	1452,	/* int_blt_un */
	1458,	/* float_beq */
	1464,	/* float_bge */
	1470,	/* float_bgt */
	1476,	/* float_ble */
	1482,	/* float_blt */
	1488,	/* float_bne_un */
	1494,	/* float_bge_un */
	1500,	/* float_bgt_un */
	1506,	/* float_ble_un */
	1512,	/* float_blt_un */
	1518,	/* float_add */
	1524,	/* float_sub */
	1530,	/* float_mul */
	1536,	/* float_div */
	1542,	/* float_div_un */
	1548,	/* float_rem */
	1554,	/* float_rem_un */
	1560,	/* float_neg */
	1566,	/* float_not */
	1572,	/* float_conv_to_i1 */
	1578,	/* float_conv_to_i2 */
	1584,	/* float_conv_to_i4 */
	1590,	/* float_conv_to_i8 */
	1596,	/* float_conv_to_r4 */
	0,	/* float_conv_to_r8 */
	1602,	/* float_conv_to_u4 */
	1608,	/* float_conv_to_u8 */
	1614,	/* float_conv_to_u2 */
	1620,	/* float_conv_to_u1 */
	1626,	/* float_conv_to_i */
	0,	/* float_conv_to_ovf_i */
	0,	/* float_conv_to_ovd_u */
	0,	/* float_add_ovf */
	0,	/* float_add_ovf_un */
	0,	/* float_mul_ovf */
	0,	/* float_mul_ovf_un */
	0,	/* float_sub_ovf */
	0,	/* float_sub_ovf_un */
	0,	/* float_conv_to_ovf_i1_un */
	0,	/* float_conv_to_ovf_i2_un */
	0,	/* float_conv_to_ovf_i4_un */
	0,	/* float_conv_to_ovf_i8_un */
	0,	/* float_conv_to_ovf_u1_un */
	0,	/* float_conv_to_ovf_u2_un */
	0,	/* float_conv_to_ovf_u4_un */
	0,	/* float_conv_to_ovf_u8_un */
	0,	/* float_conv_to_ovf_i_un */
	0,	/* float_conv_to_ovf_u_un */
	0,	/* float_conv_to_ovf_i1 */
	0,	/* float_conv_to_ovf_u1 */
	0,	/* float_conv_to_ovf_i2 */
	0,	/* float_conv_to_ovf_u2 */
	0,	/* float_conv_to_ovf_i4 */
	0,	/* float_conv_to_ovf_u4 */
	0,	/* float_conv_to_ovf_i8 */
	0,	/* float_conv_to_ovf_u8 */
	1632,	/* float_ceq */
	1638,	/* float_cgt */
	1644,	/* float_cgt_un */
	1650,	/* float_clt */
	1656,	/* float_clt_un */
	0,	/* float_ceq_membase */
	0,	/* float_cgt_membase */
	0,	/* float_cgt_un_membase */
	0,	/* float_clt_membase */
	0,	/* float_clt_un_membase */
	1662,	/* float_conv_to_u */
	1668,	/* ckfinite */
	0,	/* float_getlow32 */
	0,	/* float_gethigh32 */
	1674,	/* jump_table */
	1680,	/* aot_const */
	0,	/* patch_info */
	1686,	/* got_entry */
	1692,	/* call_handler */
	1698,	/* start_handler */
	1704,	/* endfilter */
	1710,	/* endfinally */
	1716,	/* bigmul */
	1722,	/* bigmul_un */
	0,	/* int_min_un */
	0,	/* int_max_un */
	0,	/* long_min_un */
	0,	/* long_max_un */
	0,	/* min */
	0,	/* max */
	0,	/* int_min */
	0,	/* int_max */
	0,	/* long_min */
	0,	/* long_max */
	1728,	/* adc */
	0,	/* adc_imm */
	1734,	/* sbb */
	0,	/* sbb_imm */
	1740,	/* addcc */
	1746,	/* addcc_imm */
	1752,	/* subcc */
	0,	/* subcc_imm */
	1758,	/* br_reg */
	0,	/* sext_i1 */
	0,	/* sext_i2 */
	1764,	/* sext_i4 */
	0,	/* zext_i1 */
	0,	/* zext_i2 */
	1770,	/* zext_i4 */
	0,	/* cne */
	0,	/* trunc_i4 */
	1776,	/* add_ovf_carry */
	1782,	/* sub_ovf_carry */
	1788,	/* add_ovf_un_carry */
	1794,	/* sub_ovf_un_carry */
	0,	/* sin */
	0,	/* cos */
	0,	/* abs */
	0,	/* tan */
	0,	/* atan */
	1800,	/* sqrt */
	0,	/* round */
	0,	/* strlen */
	0,	/* newarr */
	0,	/* ldlen */
	0,	/* bounds_check */
	0,	/* getldelema2 */
	0,	/* memcpy */
	0,	/* memset */
	0,	/* save_lmf */
	0,	/* restore_lmf */
	1806,	/* tls_get */
	1812,	/* load_gotaddr */
	1818,	/* dummy_use */
	1824,	/* dummy_store */
	1830,	/* not_reached */
	1836,	/* not_null */
	0,	/* xmove */
	0,	/* xzero */
	0,	/* xphi */
	0,	/* atomic_add_i4 */
	1842,	/* atomic_add_new_i4 */
	0,	/* atomic_add_imm_i4 */
	0,	/* atomic_add_imm_new_i4 */
	0,	/* atomic_exchange_i4 */
	0,	/* atomic_add_i8 */
	1848,	/* atomic_add_new_i8 */
	0,	/* atomic_add_imm_i8 */
	0,	/* atomic_add_imm_new_i8 */
	0,	/* atomic_exchange_i8 */
	1854,	/* memory_barrier */
	1860,	/* atomic_cas_i4 */
	1866,	/* atomic_cas_i8 */
	0,	/* cmov_ieq */
	0,	/* cmov_ige */
	0,	/* cmov_igt */
	0,	/* cmov_ile */
	0,	/* cmov_ilt */
	0,	/* cmov_ine_un */
	0,	/* cmov_ige_un */
	0,	/* cmov_igt_un */
	0,	/* cmov_ile_un */
	0,	/* cmov_ilt_un */
	0,	/* cmov_leq */
	0,	/* cmov_lge */
	0,	/* cmov_lgt */
	0,	/* cmov_lle */
	0,	/* cmov_llt */
	0,	/* cmov_lne_un */
	0,	/* cmov_lge_un */
	0,	/* cmov_lgt_un */
	0,	/* cmov_lle_un */
	0,	/* cmov_llt_un */
	0,	/* liverange_start */
	0,	/* liverange_end */
	1872,	/* ppc_subfic */
	1878,	/* ppc_subfze */
	1884,	/* ppc_check_finite */
};

